# Generated by Django 4.2 on 2024-10-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloScrum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='backlog_sprint',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='equipo_desarrollo',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='scrum_master',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='dependencias',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='sprint_asignado',
        ),
        migrations.DeleteModel(
            name='Epica',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
