# Generated by Django 4.2 on 2024-10-23 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ModeloScrum', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epica',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='backlog_sprint',
            field=models.ManyToManyField(related_name='backlogs', to='ModeloScrum.tarea'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='equipo_desarrollo',
            field=models.ManyToManyField(related_name='sprints_equipo', to=settings.AUTH_USER_MODEL),
        ),
    ]
