# Generated by Django 4.2 on 2024-10-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloScrum', '0004_alter_epica_fecha_inicio_alter_sprint_backlog_sprint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='backlog_sprint',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='equipo_desarrollo',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='scrum_master',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='dependencias',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='sprint_asignado',
        ),
        migrations.DeleteModel(
            name='Epica',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
